### ISSUE TITLE
Slide-pack?

### ISSUE THREAD

**Issue by uglow** [joemaddalone/advanced-directives#1]
Hi Joe,

Thanks for publishing this repo. I attended this workshop at ngConf-2015 in SLC. Was there a slide pack that accompanied it? I was hoping to re-present this at my company so that more devs can benefit from your wisdom :)

Cheers,
Brett

**Comment by joemaddalone** [comment]
Sorry, there were no slides.  My portion of the workshop was all live coding.  The code in the examples directory should match up pretty well with what I live coded.  Best of luck with leveling up your co-workers, it's a noble pursuit!

**Comment by uglow** [comment]
Thanks Joe :+1:
